"""\
ME 144/244: Modeling, Simulation, and Digital Twins of Drone-Based Systems
Project 3: Swarm
Spring 2026 Semester
GSI - Tommy Hosmer

Write fixed simulation + GA parameters to parameters.pkl.

This is intentionally separated from the simulation code so the notebook/scripts
can load a single dictionary of constants.
"""

from __future__ import annotations

import pickle

import numpy as np


# -----------------------
# System / object counts
# -----------------------
Nm = 15  # number of initial agents
No = 25  # number of obstacles
Nt = 100  # number of targets to map


# -----------------------
# Physical parameters
# -----------------------
Ai = 1.0  # agent characteristic area (m^2)
Cdi = 0.25  # agent coefficient of drag
mi = 10.0  # agent mass (kg)
va = np.array([0.0, 0.0, 0.0], dtype=float)  # air velocity (m/s)
ra = 1.225  # air density (kg/m^3)
Fp = 200.0  # propulsion force magnitude (N)


# -----------------------
# Time stepping
# -----------------------
dt = 0.2  # time step size (s)
tf = 60.0  # maximum task time (s)


# -----------------------
# Interaction parameters
# -----------------------
agent_sight = 5.0  # maximum target mapping distance
crash_range = 2.0  # agent collision distance


# -----------------------
# Genetic Algorithm (GA)
# -----------------------
# Genetic Algorithm hyperparameters (from the assignment Variable Glossary)
K = 6  # strings generated by breeding (children)
P = 6  # surviving strings for breeding (parents)

S = 20  # design strings per generation (population size)
G = 100  # total generations

minLam = 0.0  # minimum value of design variables
maxLam = 2.0  # maximum value of design variables
numLam = 15  # number of design variables in the genome

w1 = 70.0  # weight of mapping in net cost
w2 = 10.0  # weight of time usage in net cost
w3 = 20.0  # weight of agent losses in net cost


# -----------------------
# Domain parameters
# -----------------------
# Crash if agent leaves these bounds
xmax = 150.0
ymax = 150.0
zmax = 60.0

# Placement region for targets/obstacles
locx = 100.0
locy = 100.0
locz = 10.0


# GA stop threshold used by the scaffold
tolerance = 0.01


parameters_dict = {
    "Nm": Nm,
    "No": No,
    "Nt": Nt,
    "Ai": Ai,
    "Cdi": Cdi,
    "mi": mi,
    "va": va,
    "ra": ra,
    "Fp": Fp,
    "dt": dt,
    "tf": tf,
    "agent_sight": agent_sight,
    "crash_range": crash_range,
    "K": K,
    "P": P,
    "S": S,
    "G": G,
    "minLam": minLam,
    "maxLam": maxLam,
    "numLam": numLam,
    "w1": w1,
    "w2": w2,
    "w3": w3,
    "xmax": xmax,
    "ymax": ymax,
    "zmax": zmax,
    "locx": locx,
    "locy": locy,
    "locz": locz,
    "tolerance": tolerance,
}


if __name__ == "__main__":
    with open("parameters.pkl", "wb") as pkl_file:
        pickle.dump(parameters_dict, pkl_file)
