"""
ME 144/244: Modeling, Simulation, and Digital Twins of Drone-Based Systems 
Project 2: Swarm
Spring 2026 Semester
GSI - Tommy Hosmer
"""
import pickle
"""
This script writes the parameters to a dictionary in a pickle file that can be read in during the simulation. 
Separating from full sim makes things cleaner.
"""

# System Parameters
Nm =                                         # number of initial agents
No =                                         # number of obstacles
Nt =                                         # number of targets to map

# Physical Parameters
Ai  =                            # agent characteristic area (m^2)
Cdi =                            # agent coefficient of drag
mi  =                            # agent mass (kg)
va  =                            # Air velocity (m/s)
ra  =                            # Air Density (kg/m^3)
Fp  =                            # Propulsion force magnitude (N)

# Time Stepping Parameters
dt =                                         # time step size (s)
tf =                                         # Maximum task time (s)

# Object Interaction Parameters
agent_sight =                                  # maximum target mapping distance
crash_range =                                  # agent collision distance

# Genetic Algorithm Parameters
K =                                           # Strings generated by breeding (Children)
P =                                           # Surviving strings for breeding (Parents)
S =                                           # Design strings per generation
G =                                           # Total Generations
minLam =                                      # Minimum value of design strings
maxLam =                                      # Maximum value of design strings
numLam = 

w1 =                                          # Weight of mapping in net cost
w2 =                                          # Weight of time usage in net cost
w3 =                                          # Weight of agent losses in net cost

# Domain Parameters
xmax =                                       # x bound of domain
ymax =                                       # y bound of domain
zmax =                                       # z bound of domain

locx =                                       # x bound of target/obstacle region
locy =                                       # y bound of target/obstacle region
locz = 
tolerance = 0.01

# Store the parameters in a dictionary
parameters_dict = {
    "Nm": Nm,
    "No": No,
    "Nt": Nt,
    "Ai": Ai,
    "Cdi": Cdi,
    "mi": mi,
    "va": va,
    "ra": ra,
    "Fp": Fp,
    "dt": dt,
    "tf": tf,
    "agent_sight": agent_sight,
    "crash_range": crash_range,
    "K": K,
    "P": P,
    "S": S,
    "G": G,
    "minLam": minLam,
    "maxLam": maxLam,
    "numLam": numLam,
    "w1": w1,
    "w2": w2,
    "w3": w3,
    "xmax": xmax,
    "ymax": ymax,
    "zmax": zmax,
    "locx": locx,
    "locy": locy,
    "locz": locz,
    "tolerance": tolerance
}

# Write the dictionary to a pickle file

with open('parameters.pkl', 'wb') as pkl_file:
    pickle.dump(parameters_dict, pkl_file)
